[mgr]
show_hidden = true
show_symlink = true
wrap = "no"
tab_size = 4
cursor_blink = true

[preview]
tab_size = 4

[opener]
play = [
    { run = "mpv %s", orphan = true, desc = "Play with MPV" },
    { run = "vlc %s", orphan = true, desc = "Play with VLC" },
]

edit = [
    { run = "$EDITOR %s", block = true, desc = "Edit with default editor" },
    { run = "zeditor %s", block = false, orphan = true, desc = "Edit with Zed Editor" },
    { run = "code %s", block = false, orphan = true, desc = "Edit with VSCode" },
]

[input]
cursor_blink = true

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "git"
