#!/usr/bin/env python3

from pydbus import SessionBus
from json import dumps
from sys import stdout

bus = SessionBus()

dbusInterface = bus.get('org.gnome.Pomodoro', '/org/gnome/Pomodoro')

def format_time(time):
    minutes, seconds = divmod(time, 60)
    minutes = int(minutes)
    seconds = int(seconds)
    return f"{minutes:02d}:{seconds:02d}"

class PomodoroSession:
    dbus_interface = None
    State = "stopped"
    IsPaused = False
    Elapsed = 0
    StateDuration = 0

    def __init__(self, dbus_interface):
        self.dbus_interface = dbus_interface
        self.initialize()

    def initialize(self):
        if self.dbus_interface == None or self.dbus_interface.State == "null" or self.dbus_interface.State == "stopped":
            return

        self.State = self.dbus_interface.State
        self.IsPaused = self.dbus_interface.IsPaused
        self.Elapsed = self.dbus_interface.Elapsed
        self.StateDuration = self.dbus_interface.StateDuration

    def stop(self):
        self.State = "stopped"
        self.IsPaused = False
        self.Elapsed = 0
        self.StateDuration = 0

    def update(self, key, value):
        if (key == "State") and (not value or value == "null" or value == "stopped"):
            self.stop()
        elif key == "StateDuration" and value == 0.0:
            self.stop()

        if hasattr(self, key):
            setattr(self, key, value)

    def Progress(self):
        if self.StateDuration == 0:
            return 0

        return int((self.Elapsed / self.StateDuration) * 100)

    def waybarJSON(self):
        text = "Stopped"
        alt_text = "Pomodoro stopped"
        tooltip = "Pomodoro session not started"
        percentage = 0
        css_class = "stopped"

        if self.State != "stopped":
            formated_remaining = format_time(self.StateDuration - self.Elapsed)
            formated_elapsed = format_time(self.Elapsed)
            formated_duration = format_time(self.StateDuration)
            state = self.State.title().replace("-", " ")

            text = formated_remaining
            alt_text = f"{formated_elapsed}/{formated_duration}"
            tooltip = f"Session: {state}\rRemaining: {formated_remaining}\rElapsed: {formated_elapsed}\rDuration: {formated_duration}"
            percentage = self.Progress()

            isPausedState = "running" if not self.IsPaused else "paused"
            css_class = [ isPausedState, self.State ]

        return dumps({
            "text": text,
            "alt": alt_text,
            "tooltip": tooltip,
            "class": css_class,
            "percentage": percentage
        })

def print_waybar_json():
    print(pomodoroSection.waybarJSON())
    stdout.flush()

pomodoroSection = PomodoroSession(dbusInterface)
print_waybar_json()

def updateState(_interfaceName, valuesChanged, _invalidated):
    global pomodoroSection

    for key, value in valuesChanged.items():
        pomodoroSection.update(key, value)

    print_waybar_json()

dbusInterface.onPropertiesChanged = updateState

from gi.repository import GLib

loop = GLib.MainLoop()

loop.run()
